In [225]:
import pandas as pd
def load_user_data()->pd.DataFrame:
    df=pd.read_json("../users.json",dtype={"national_id": str})
    return df
def load_transaction_data()->pd.DataFrame:
    df=pd.read_json("../transactions.json")
    return df
users=load_user_data()
print(users)

     user_id first_name last_name                                email  \
0   CUST0000     kabelo   dlamini      kabelo.dlamini859@example.co.za
1   CUST0001      sipho    ngcobo        sipho.ngcobo814@example.co.za
2   CUST0002    bongani   motsepe     bongani.motsepe296@example.co.za
3   cust0003     themba  mahlangu     themba.mahlangu801@example.co.za
4   CUST0004     zanele   sithole      zanele.sithole324@example.co.za
5   CUST0005       mpho     ntuli          mpho.ntuli261@example.co.za
6   CUST0006       mpho  mahlangu       mpho.mahlangu159@example.co.za
7   CUST0007   lebohang    gumede     lebohang.gumede223@example.co.za
8   CUST0008  nokuthula   motsepe   nokuthula.motsepe584@example.co.za
9   CUST0009     naledi     nkosi        naledi.nkosi553@example.co.za
10  CUST0010     themba      cele         themba.cele258@example.co.za
11  CUST0011  nokuthula  mahlangu  nokuthula.mahlangu692@example.co.za
12  CUST0012       jabu   maponya        jabu.maponya318@example.co.za
13  CUST0013       mpho    ndlovu         mpho.ndlovu834@example.co.za
14  CUST0014     tshepo   maponya      tshepo.maponya136@example.co.za
15  CUST0015      sipho    ngcobo        sipho.ngcobo854@example.co.za
16  CUST0016   lebohang     zwane      lebohang.zwane795@example.co.za
17  CUST0017     themba    ndlovu       themba.ndlovu472@example.co.za
18  CUST0018       mpho    ndlovu         mpho.ndlovu540@example.co.za
19  CUST0019       jabu    gumede         jabu.gumede524@example.co.za
20  CUST0020   kgomotso   msimang    kgomotso.msimang536@example.co.za
21  CUST0021      nomsa     nkosi         nomsa.nkosi524@example.co.za
22  CUST0022    lindiwe     ntuli       lindiwe.ntuli597@example.co.za
23  CUST0023     zanele      pule         zanele.pule870@example.co.za
24  CUST0024    bongani    ngcobo      bongani.ngcobo720@example.co.za
25  CUST0025   lebohang    mabaso     lebohang.mabaso112@example.co.za
26  CUST0026  nokuthula     zwane     nokuthula.zwane444@example.co.za
27  CUST0027     palesa    gumede       palesa.gumede911@example.co.za
28  CUST0028     themba    ngcobo       themba.ngcobo296@example.co.za
29  CUST0029     palesa   mthembu      palesa.mthembu993@example.co.za
30  cust0003     themba  mahlangu     themba.mahlangu801@example.co.za

                                             location   account_created  \
0   {'city': 'Port Elizabeth', 'country': 'South A...  20-02-2023-13-11
1    {'city': 'Polokwane', 'country': 'South Africa'}  22-12-2024-00-25
2    {'city': 'Cape Town', 'country': 'South Africa'}  29-06-2020-01-40
3   {'city': 'Bloemfontein', 'country': 'South Afr...  15-11-2021-13-36
4       {'city': 'Durban', 'country': 'South Africa'}  12-05-2021-23-47
5    {'city': 'Nelspruit', 'country': 'South Africa'}  01-09-2023-12-33
6     {'city': 'Pretoria', 'country': 'South Africa'}  10-11-2024-21-36
7     {'city': 'Pretoria', 'country': 'South Africa'}              None
8     {'city': 'Pretoria', 'country': 'South Africa'}  25-10-2024-09-26
9    {'city': 'Kimberley', 'country': 'South Africa'}  24-07-2022-03-00
10    {'city': 'Pretoria', 'country': 'South Africa'}  29-12-2022-16-27
11  {'city': 'Pietermaritzburg', 'country': 'South...  21-03-2024-07-21
12   {'city': 'Kimberley', 'country': 'South Africa'}  07-07-2023-14-35
13  {'city': 'Bloemfontein', 'country': 'South Afr...  09-10-2020-13-34
14  {'city': 'Bloemfontein', 'country': 'South Afr...  20-08-2024-16-33
15  {'city': 'Bloemfontein', 'country': 'South Afr...  31-01-2025-11-18
16   {'city': 'Kimberley', 'country': 'South Africa'}  22-11-2023-06-18
17   {'city': 'Polokwane', 'country': 'South Africa'}  04-02-2024-16-44
18  {'city': 'Pietermaritzburg', 'country': 'South...  2021/12/02 04:55
19  {'city': 'Pietermaritzburg', 'country': 'South...  08-07-2020-02-54
20   {'city': 'Kimberley', 'country': 'South Africa'}  2023/07/22 06:46
21   {'city': 'Polokwane', 'country': 'South Africa'}  24-09-2024-13-49
22  {'city': 'Johannesburg', 'country': 'South Afr...  2024/10/30 01:22
23   {'city': 'Polokwane', 'country': 'South Africa'}  2023/03/18 23:49
24  {'city': 'Pietermaritzburg', 'country': 'South...  15-09-2020-01-16
25   {'city': 'Polokwane', 'country': 'South Africa'}  02-08-2021-06-14
26  {'city': 'Johannesburg', 'country': 'South Afr...  14-09-2024-13-17
27  {'city': 'Johannesburg', 'country': 'South Afr...  14-03-2021-11-15
28    {'city': 'Pretoria', 'country': 'South Africa'}  04-03-2023-04-19
29  {'city': 'Johannesburg', 'country': 'South Afr...  2020/08/17 03:45
30  {'city': 'Bloemfontein', 'country': 'South Afr...  15-11-2021-13-36

             national_id internal_notes
0   33218196001338908386         note_0
1   54235116155940781618         note_1
2   03413164752553419283         note_2
3   03056413953767242388         note_3
4   87101226916697848018         note_4
5   04828148932528809570         note_5
6   91171822782489638346         note_6
7   31509839301031051834           None
8   76311656670106513338         note_8
9   10801326773602606474         note_9
10  43098050097882081219        note_10
11  09169985435346247510        note_11
12  42513542784980841241           None
13  34874016400524278680        note_13
14  98262045053315869232        note_14
15  63421607337543303654        note_15
16  50142940196556981693           None
17  15951484656482366299           None
18  95777387214895134332        note_18
19  36763201632870831727        note_19
20  72774348734714345581        note_20
21  58760366909670546688        note_21
22  65627298069901627204        note_22
23  41708053100330923271        note_23
24  12419049663193149190        note_24
25  71657262849877694531        note_25
26  75273545494808313678        note_26
27  14363495788568557444        note_27
28  74989413435240824008        note_28
29  94777520471167190229        note_29
30  03056413953767242388         note_3

In [216]:
from datetime import datetime
import pandas as pd
import numpy as np

def clean_dates(value, output_format: str = "%d/%m/%Y %H:%M:%S"):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    formats = [
        "%d-%m-%Y-%H-%M",
        "%Y/%m/%d %H:%M"
    ]

    for fmt in formats:
        try:
            parsed = datetime.strptime(value, fmt)
            return parsed.strftime(output_format)
        except ValueError:
            continue

    return np.nan

users["account_created"] = users["account_created"].apply(clean_dates)
print(users["account_created"])

0     20/02/2023 13:11:00
1     22/12/2024 00:25:00
2     29/06/2020 01:40:00
3     15/11/2021 13:36:00
4     12/05/2021 23:47:00
5     01/09/2023 12:33:00
6     10/11/2024 21:36:00
7                     NaN
8     25/10/2024 09:26:00
9     24/07/2022 03:00:00
10    29/12/2022 16:27:00
11    21/03/2024 07:21:00
12    07/07/2023 14:35:00
13    09/10/2020 13:34:00
14    20/08/2024 16:33:00
15    31/01/2025 11:18:00
16    22/11/2023 06:18:00
17    04/02/2024 16:44:00
18    02/12/2021 04:55:00
19    08/07/2020 02:54:00
20    22/07/2023 06:46:00
21    24/09/2024 13:49:00
22    30/10/2024 01:22:00
23    18/03/2023 23:49:00
24    15/09/2020 01:16:00
25    02/08/2021 06:14:00
26    14/09/2024 13:17:00
27    14/03/2021 11:15:00
28    04/03/2023 04:19:00
29    17/08/2020 03:45:00
30    15/11/2021 13:36:00
Name: account_created, dtype: object

In [196]:
print(users.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          31 non-null     object
 1   first_name       31 non-null     object
 2   last_name        31 non-null     object
 3   email            31 non-null     object
 4   location         31 non-null     object
 5   account_created  30 non-null     object
 6   national_id      31 non-null     object
 7   internal_notes   27 non-null     object
dtypes: object(8)
memory usage: 2.1+ KB
None

In [ ]:
def correct_to_uppercase(string:str):
    return string.upper() if not string.isupper() else string

In [217]:
users["user_id"]=users["user_id"].apply(correct_to_uppercase)

In [155]:
for i in users["user_id"]:
    print(i)

CUST0000
CUST0001
CUST0002
CUST0003
CUST0004
CUST0005
CUST0006
CUST0007
CUST0008
CUST0009
CUST0010
CUST0011
CUST0012
CUST0013
CUST0014
CUST0015
CUST0016
CUST0017
CUST0018
CUST0019
CUST0020
CUST0021
CUST0022
CUST0023
CUST0024
CUST0025
CUST0026
CUST0027
CUST0028
CUST0029
CUST0003

In [218]:
users=users.drop_duplicates(subset=["user_id","first_name","last_name","email","account_created","national_id","internal_notes"])
print(users.info())

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          30 non-null     object
 1   first_name       30 non-null     object
 2   last_name        30 non-null     object
 3   email            30 non-null     object
 4   location         30 non-null     object
 5   account_created  29 non-null     object
 6   national_id      30 non-null     object
 7   internal_notes   26 non-null     object
dtypes: object(8)
memory usage: 2.1+ KB
None

In [157]:
for email in users["email"]:
    print(email[1:])

abelo.dlamini859@example.co.za
ipho.ngcobo814@example.co.za
ongani.motsepe296@example.co.za
hemba.mahlangu801@example.co.za
anele.sithole324@example.co.za
pho.ntuli261@example.co.za
pho.mahlangu159@example.co.za
ebohang.gumede223@example.co.za
okuthula.motsepe584@example.co.za
aledi.nkosi553@example.co.za
hemba.cele258@example.co.za
okuthula.mahlangu692@example.co.za
abu.maponya318@example.co.za
pho.ndlovu834@example.co.za
shepo.maponya136@example.co.za
ipho.ngcobo854@example.co.za
ebohang.zwane795@example.co.za
hemba.ndlovu472@example.co.za
pho.ndlovu540@example.co.za
abu.gumede524@example.co.za
gomotso.msimang536@example.co.za
omsa.nkosi524@example.co.za
indiwe.ntuli597@example.co.za
anele.pule870@example.co.za
ongani.ngcobo720@example.co.za
ebohang.mabaso112@example.co.za
okuthula.zwane444@example.co.za
alesa.gumede911@example.co.za
hemba.ngcobo296@example.co.za
alesa.mthembu993@example.co.za

In [219]:

def hide_email(email: str) -> str:
    at_index = email.find('@')
    hidden_part = '*' * (at_index - 1)
    return email[0] + hidden_part + email[at_index:]

users["email"]=users["email"].apply(hide_email)
print(users)

     user_id first_name last_name                                email  \
0   CUST0000     kabelo   dlamini      k****************@example.co.za
1   CUST0001      sipho    ngcobo        s**************@example.co.za
2   CUST0002    bongani   motsepe     b*****************@example.co.za
3   CUST0003     themba  mahlangu     t*****************@example.co.za
4   CUST0004     zanele   sithole      z****************@example.co.za
5   CUST0005       mpho     ntuli          m************@example.co.za
6   CUST0006       mpho  mahlangu       m***************@example.co.za
7   CUST0007   lebohang    gumede     l*****************@example.co.za
8   CUST0008  nokuthula   motsepe   n*******************@example.co.za
9   CUST0009     naledi     nkosi        n**************@example.co.za
10  CUST0010     themba      cele         t*************@example.co.za
11  CUST0011  nokuthula  mahlangu  n********************@example.co.za
12  CUST0012       jabu   maponya        j**************@example.co.za
13  CUST0013       mpho    ndlovu         m*************@example.co.za
14  CUST0014     tshepo   maponya      t****************@example.co.za
15  CUST0015      sipho    ngcobo        s**************@example.co.za
16  CUST0016   lebohang     zwane      l****************@example.co.za
17  CUST0017     themba    ndlovu       t***************@example.co.za
18  CUST0018       mpho    ndlovu         m*************@example.co.za
19  CUST0019       jabu    gumede         j*************@example.co.za
20  CUST0020   kgomotso   msimang    k******************@example.co.za
21  CUST0021      nomsa     nkosi         n*************@example.co.za
22  CUST0022    lindiwe     ntuli       l***************@example.co.za
23  CUST0023     zanele      pule         z*************@example.co.za
24  CUST0024    bongani    ngcobo      b****************@example.co.za
25  CUST0025   lebohang    mabaso     l*****************@example.co.za
26  CUST0026  nokuthula     zwane     n*****************@example.co.za
27  CUST0027     palesa    gumede       p***************@example.co.za
28  CUST0028     themba    ngcobo       t***************@example.co.za
29  CUST0029     palesa   mthembu      p****************@example.co.za

                                             location      account_created  \
0   {'city': 'Port Elizabeth', 'country': 'South A...  20/02/2023 13:11:00
1    {'city': 'Polokwane', 'country': 'South Africa'}  22/12/2024 00:25:00
2    {'city': 'Cape Town', 'country': 'South Africa'}  29/06/2020 01:40:00
3   {'city': 'Bloemfontein', 'country': 'South Afr...  15/11/2021 13:36:00
4       {'city': 'Durban', 'country': 'South Africa'}  12/05/2021 23:47:00
5    {'city': 'Nelspruit', 'country': 'South Africa'}  01/09/2023 12:33:00
6     {'city': 'Pretoria', 'country': 'South Africa'}  10/11/2024 21:36:00
7     {'city': 'Pretoria', 'country': 'South Africa'}                  NaN
8     {'city': 'Pretoria', 'country': 'South Africa'}  25/10/2024 09:26:00
9    {'city': 'Kimberley', 'country': 'South Africa'}  24/07/2022 03:00:00
10    {'city': 'Pretoria', 'country': 'South Africa'}  29/12/2022 16:27:00
11  {'city': 'Pietermaritzburg', 'country': 'South...  21/03/2024 07:21:00
12   {'city': 'Kimberley', 'country': 'South Africa'}  07/07/2023 14:35:00
13  {'city': 'Bloemfontein', 'country': 'South Afr...  09/10/2020 13:34:00
14  {'city': 'Bloemfontein', 'country': 'South Afr...  20/08/2024 16:33:00
15  {'city': 'Bloemfontein', 'country': 'South Afr...  31/01/2025 11:18:00
16   {'city': 'Kimberley', 'country': 'South Africa'}  22/11/2023 06:18:00
17   {'city': 'Polokwane', 'country': 'South Africa'}  04/02/2024 16:44:00
18  {'city': 'Pietermaritzburg', 'country': 'South...  02/12/2021 04:55:00
19  {'city': 'Pietermaritzburg', 'country': 'South...  08/07/2020 02:54:00
20   {'city': 'Kimberley', 'country': 'South Africa'}  22/07/2023 06:46:00
21   {'city': 'Polokwane', 'country': 'South Africa'}  24/09/2024 13:49:00
22  {'city': 'Johannesburg', 'country': 'South Afr...  30/10/2024 01:22:00
23   {'city': 'Polokwane', 'country': 'South Africa'}  18/03/2023 23:49:00
24  {'city': 'Pietermaritzburg', 'country': 'South...  15/09/2020 01:16:00
25   {'city': 'Polokwane', 'country': 'South Africa'}  02/08/2021 06:14:00
26  {'city': 'Johannesburg', 'country': 'South Afr...  14/09/2024 13:17:00
27  {'city': 'Johannesburg', 'country': 'South Afr...  14/03/2021 11:15:00
28    {'city': 'Pretoria', 'country': 'South Africa'}  04/03/2023 04:19:00
29  {'city': 'Johannesburg', 'country': 'South Afr...  17/08/2020 03:45:00

             national_id internal_notes
0   33218196001338908386         note_0
1   54235116155940781618         note_1
2   03413164752553419283         note_2
3   03056413953767242388         note_3
4   87101226916697848018         note_4
5   04828148932528809570         note_5
6   91171822782489638346         note_6
7   31509839301031051834           None
8   76311656670106513338         note_8
9   10801326773602606474         note_9
10  43098050097882081219        note_10
11  09169985435346247510        note_11
12  42513542784980841241           None
13  34874016400524278680        note_13
14  98262045053315869232        note_14
15  63421607337543303654        note_15
16  50142940196556981693           None
17  15951484656482366299           None
18  95777387214895134332        note_18
19  36763201632870831727        note_19
20  72774348734714345581        note_20
21  58760366909670546688        note_21
22  65627298069901627204        note_22
23  41708053100330923271        note_23
24  12419049663193149190        note_24
25  71657262849877694531        note_25
26  75273545494808313678        note_26
27  14363495788568557444        note_27
28  74989413435240824008        note_28
29  94777520471167190229        note_29

In [ ]:

location_data = pd.json_normalize(users["location"].to_list())
users = users.drop(columns=["location"])
users = pd.concat([users, location_data], axis=1)

In [227]:

print(users.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          31 non-null     object
 1   first_name       31 non-null     object
 2   last_name        31 non-null     object
 3   email            31 non-null     object
 4   account_created  30 non-null     object
 5   national_id      31 non-null     object
 6   internal_notes   27 non-null     object
 7   city             31 non-null     object
 8   country          31 non-null     object
dtypes: object(9)
memory usage: 2.3+ KB
None

In [186]:
def hide_national_id(id:str):
    id=str(id)
    return id[:3]+"X"*len(id[3:])

users["national_id"]=users["national_id"].apply(hide_national_id)
print(users)

     user_id first_name last_name                                email  \
0   CUST0000     kabelo   dlamini      k****************@example.co.za
1   CUST0001      sipho    ngcobo        s**************@example.co.za
2   CUST0002    bongani   motsepe     b*****************@example.co.za
3   CUST0003     themba  mahlangu     t*****************@example.co.za
4   CUST0004     zanele   sithole      z****************@example.co.za
5   CUST0005       mpho     ntuli          m************@example.co.za
6   CUST0006       mpho  mahlangu       m***************@example.co.za
7   CUST0007   lebohang    gumede     l*****************@example.co.za
8   CUST0008  nokuthula   motsepe   n*******************@example.co.za
9   CUST0009     naledi     nkosi        n**************@example.co.za
10  CUST0010     themba      cele         t*************@example.co.za
11  CUST0011  nokuthula  mahlangu  n********************@example.co.za
12  CUST0012       jabu   maponya        j**************@example.co.za
13  CUST0013       mpho    ndlovu         m*************@example.co.za
14  CUST0014     tshepo   maponya      t****************@example.co.za
15  CUST0015      sipho    ngcobo        s**************@example.co.za
16  CUST0016   lebohang     zwane      l****************@example.co.za
17  CUST0017     themba    ndlovu       t***************@example.co.za
18  CUST0018       mpho    ndlovu         m*************@example.co.za
19  CUST0019       jabu    gumede         j*************@example.co.za
20  CUST0020   kgomotso   msimang    k******************@example.co.za
21  CUST0021      nomsa     nkosi         n*************@example.co.za
22  CUST0022    lindiwe     ntuli       l***************@example.co.za
23  CUST0023     zanele      pule         z*************@example.co.za
24  CUST0024    bongani    ngcobo      b****************@example.co.za
25  CUST0025   lebohang    mabaso     l*****************@example.co.za
26  CUST0026  nokuthula     zwane     n*****************@example.co.za
27  CUST0027     palesa    gumede       p***************@example.co.za
28  CUST0028     themba    ngcobo       t***************@example.co.za
29  CUST0029     palesa   mthembu      p****************@example.co.za

        account_created           national_id internal_notes  \
0   20/02/2023 13:11:00  332XXXXXXXXXXXXXXXXX         note_0
1   22/12/2024 00:25:00  542XXXXXXXXXXXXXXXXX         note_1
2   29/06/2020 01:40:00  034XXXXXXXXXXXXXXXXX         note_2
3   15/11/2021 13:36:00  030XXXXXXXXXXXXXXXXX         note_3
4   12/05/2021 23:47:00  871XXXXXXXXXXXXXXXXX         note_4
5   01/09/2023 12:33:00  048XXXXXXXXXXXXXXXXX         note_5
6   10/11/2024 21:36:00  911XXXXXXXXXXXXXXXXX         note_6
7                   NaN  315XXXXXXXXXXXXXXXXX           None
8   25/10/2024 09:26:00  763XXXXXXXXXXXXXXXXX         note_8
9   24/07/2022 03:00:00  108XXXXXXXXXXXXXXXXX         note_9
10  29/12/2022 16:27:00  430XXXXXXXXXXXXXXXXX        note_10
11  21/03/2024 07:21:00  091XXXXXXXXXXXXXXXXX        note_11
12  07/07/2023 14:35:00  425XXXXXXXXXXXXXXXXX           None
13  09/10/2020 13:34:00  348XXXXXXXXXXXXXXXXX        note_13
14  20/08/2024 16:33:00  982XXXXXXXXXXXXXXXXX        note_14
15  31/01/2025 11:18:00  634XXXXXXXXXXXXXXXXX        note_15
16  22/11/2023 06:18:00  501XXXXXXXXXXXXXXXXX           None
17  04/02/2024 16:44:00  159XXXXXXXXXXXXXXXXX           None
18  02/12/2021 04:55:00  957XXXXXXXXXXXXXXXXX        note_18
19  08/07/2020 02:54:00  367XXXXXXXXXXXXXXXXX        note_19
20  22/07/2023 06:46:00  727XXXXXXXXXXXXXXXXX        note_20
21  24/09/2024 13:49:00  587XXXXXXXXXXXXXXXXX        note_21
22  30/10/2024 01:22:00  656XXXXXXXXXXXXXXXXX        note_22
23  18/03/2023 23:49:00  417XXXXXXXXXXXXXXXXX        note_23
24  15/09/2020 01:16:00  124XXXXXXXXXXXXXXXXX        note_24
25  02/08/2021 06:14:00  716XXXXXXXXXXXXXXXXX        note_25
26  14/09/2024 13:17:00  752XXXXXXXXXXXXXXXXX        note_26
27  14/03/2021 11:15:00  143XXXXXXXXXXXXXXXXX        note_27
28  04/03/2023 04:19:00  749XXXXXXXXXXXXXXXXX        note_28
29  17/08/2020 03:45:00  947XXXXXXXXXXXXXXXXX        note_29

                city       country
0     Port Elizabeth  South Africa
1          Polokwane  South Africa
2          Cape Town  South Africa
3       Bloemfontein  South Africa
4             Durban  South Africa
5          Nelspruit  South Africa
6           Pretoria  South Africa
7           Pretoria  South Africa
8           Pretoria  South Africa
9          Kimberley  South Africa
10          Pretoria  South Africa
11  Pietermaritzburg  South Africa
12         Kimberley  South Africa
13      Bloemfontein  South Africa
14      Bloemfontein  South Africa
15      Bloemfontein  South Africa
16         Kimberley  South Africa
17         Polokwane  South Africa
18  Pietermaritzburg  South Africa
19  Pietermaritzburg  South Africa
20         Kimberley  South Africa
21         Polokwane  South Africa
22      Johannesburg  South Africa
23         Polokwane  South Africa
24  Pietermaritzburg  South Africa
25         Polokwane  South Africa
26      Johannesburg  South Africa
27      Johannesburg  South Africa
28          Pretoria  South Africa
29      Johannesburg  South Africa

In [ ]:
users.to_json("../cleaned_files/cleaned_users.json",orient="records", indent=2, force_ascii=False)